#ifndef TOUCH_MUSTER_H
#define TOUCH_MUSTER_H

#define TOUCH_KERNEL_MUSTER(X)          \
    X("acpi:boot-error")                \
    X("acpi:cper:generic")              \
    X("acpi:cper:memory")               \
    X("acpi:cper:pcie")                 \
    X("acpi:cper:processor")            \
    X("acpi:power-button")              \
    X("acpi:ready")                     \
    X("acpi:sleep:s1")                  \
    X("acpi:sleep:s2")                  \
    X("acpi:sleep:s3")                  \
    X("acpi:sleep:s4")                  \
    X("aml:ready")                      \
    X("apei:generic:error")             \
    X("apei:ghes:ready")                \
    X("apei:memory:error")              \
    X("apei:pcie:error")                \
    X("apei:processor:error")           \
    X("cet:enabled")                    \
    X("cet:fault:cp")                   \
    X("display:ready")                  \
    X("efi:capsule:armed")              \
    X("efi:capsule:delivered")          \
    X("efi:capsule:set-fail")           \
    X("efi:variable:nv-info")           \
    X("esrt:ready")                     \
    X("ibt:enabled")                    \
    X("iommu:dma:mapped")               \
    X("iommu:dma:unmapped")             \
    X("iommu:domain:attached")          \
    X("iommu:fault")                    \
    X("iommu:ready")                    \
    X("keyboard")                       \
    X("mce:fault:detected")             \
    X("mce:fault:fatal")                \
    X("mce:fault:recovered")            \
    X("mce:migration:completed")        \
    X("mce:migration:failed")           \
    X("mce:migration:unmapped")         \
    X("memtag:cabin:granted")           \
    X("memtag:cabin:revoked")           \
    X("memtag:fault:denied")            \
    X("memtag:guard:set")               \
    X("memtag:region:added")            \
    X("memtag:region:released")         \
    X("memtag:tag:applied")             \
    X("memtag:tag:cleared")             \
    X("numa:topology")                  \
    X("pku:fault:denied")               \
    X("process:died")                   \
    X("process:spawned")                \
    X("seat:emptied")                   \
    X("seat:taken")                     \
    X("secureboot:audit-mode")          \
    X("secureboot:deployed-mode")       \
    X("secureboot:off")                 \
    X("secureboot:on")                  \
    X("secureboot:setup-mode")          \
    X("secureboot:user-mode")           \
    X("shstk:enabled")                  \
    X("storage:ata:error")              \
    X("strand:exited")                  \
    X("strand:parked")                  \
    X("strand:spawned")                 \
    X("strand:woken")                   \
    X("tme:keyid:rekey:failed")         \
    X("tme:pool:ready")                 \
    X("usb:arrived")                    \
    X("usb:connect")                    \
    X("usb:disconnect")                 \
    X("usb:left")                       \
    X("volume:mounted")                 \
    X("watchtest:inner")                \
    X("watchtest:one")                  \
           \
    X("pci")                            \
    X("esrt")

#endif