#ifndef KERNEL_CONFIG_H
#define KERNEL_CONFIG_H

#include "boxos_limits.h"

#define CONFIG_KERNEL_LOAD_ADDR 0x100000ULL // 1MB - kernel run address (must match linker.ld)
// PAGE_TABLE_BASE and KERNEL_STACK_BASE are now DYNAMIC — placed after kernel_end
// by the bootloader. Available at runtime via boot_info_t (boot_info.h).

#define CONFIG_USER_CODE_BASE 0x20000000ULL  // 512MB - user code start
#define CONFIG_USER_STACK_BASE 0x20100000ULL // 513MB - user stack start
#define CONFIG_USER_RINGS_BASE 0x20200000ULL // 514MB - ring buffers start

#define CONFIG_VMM_KERNEL_BASE 0xFFFF800000000000ULL
#define CONFIG_VMM_KERNEL_HEAP_SIZE (1ULL << 30)        // 1GB kernel heap
#define CONFIG_VMM_USER_BASE 0x0000000000400000ULL      // 4MB (ELF standard)
#define CONFIG_VMM_USER_STACK_TOP 0x00007FFFFFFFE000ULL // ~128TB

#define CONFIG_PAGE_SIZE 4096

#define CONFIG_PROCESS_MAX_COUNT MAX_PROCESSES
#define CONFIG_KERNEL_STACK_PAGES 4
#define CONFIG_KERNEL_STACK_GUARD_PAGES 1
#define CONFIG_KERNEL_STACK_TOTAL_PAGES (CONFIG_KERNEL_STACK_PAGES + CONFIG_KERNEL_STACK_GUARD_PAGES)
#define CONFIG_USER_STACK_SIZE_KB 64 // 64KB for shell stability
#define CONFIG_USER_STACK_SIZE (CONFIG_USER_STACK_SIZE_KB * 1024)
#define CONFIG_USER_STACK_PAGES (CONFIG_USER_STACK_SIZE / CONFIG_PAGE_SIZE)
#define CONFIG_USER_STACK_GUARD_PAGES 1
#define CONFIG_USER_STACK_TOTAL_PAGES (CONFIG_USER_STACK_PAGES + CONFIG_USER_STACK_GUARD_PAGES)

#define CONFIG_USER_HEAP_INITIAL_SIZE (64 * 1024) // 64KB initial heap
#define CONFIG_USER_HEAP_MAX_SIZE BOXOS_USER_HEAP_MAX_SIZE
#define CONFIG_USER_HEAP_INITIAL_PAGES (CONFIG_USER_HEAP_INITIAL_SIZE / CONFIG_PAGE_SIZE)

#define CONFIG_USER_BSS_SIZE (16 * 1024)

#define CONFIG_PROC_MAX_BINARY_SIZE BOXOS_PROC_MAX_BINARY_SIZE
#define CONFIG_PROC_MAX_BUFFER_SIZE BOXOS_PROC_MAX_BUFFER_SIZE

// Ring buffer capacities are defined at their source of truth:
// - Event ring: event_ring.h (EVENT_RING_MIN_CAPACITY / EVENT_RING_MAX_CAPACITY)
// - Result ring: boxos_sizes.h (RESULT_RING_SIZE)

#define CONFIG_EVENTRING_BLOCK_TIMEOUT_MS 500

#define CONFIG_TAGFS_VERSION 2
#define CONFIG_TAGFS_BLOCK_SIZE 4096
#define CONFIG_TAGFS_MAX_FILES 65536
#define CONFIG_TAGFS_MAX_FILE_SIZE (4ULL << 30) // 4GB per file
#define CONFIG_TAGFS_INODE_SIZE TAGFS_INODE_SIZE

#define CONFIG_TAGFS_MAX_TAGS_PER_FILE 32
#define CONFIG_TAGFS_TAG_KEY_SIZE 32
#define CONFIG_TAGFS_TAG_VALUE_SIZE 64
#define CONFIG_TAGFS_MAX_TAG_INDEX 1024
#define CONFIG_TAGFS_MAX_CONTEXT_TAGS 16

#define CONFIG_MAX_OPEN_FILES MAX_OPEN_FILES

#define CONFIG_MAX_TIMERS 64
#define CONFIG_PIT_FREQUENCY_HZ 100
#define CONFIG_PIT_BASE_FREQ 1193182 // PIT hardware frequency

#define CONFIG_SYSCALL_VECTOR 0x80 // INT 0x80 (kernel_notify)
#define CONFIG_IRQ_TIMER 32        // IRQ 0 -> INT 0x20

#define CONFIG_TIME_SLICE_TICKS 10         // 100ms at 100Hz (LARGE - workflow-driven!)
#define CONFIG_WATCHDOG_TIMEOUT_TICKS 1000 // 10 seconds at 100Hz
#define CONFIG_WATCHDOG_CHECK_INTERVAL 100 // 1 second at 100Hz

#define CONFIG_ATA_TIMEOUT_MS 5000
#define CONFIG_ATA_SECTOR_SIZE 512 // Hardware constant
#define CONFIG_ATA_DMA_DEBUG 0     // 0=production (errors only), 1=verbose debug
#define CONFIG_ATA_DMA_ASYNC 1
#define CONFIG_ATA_MAX_RETRIES 3

#define CONFIG_ASYNC_DISPATCH_INTERVAL_MS 1
#define CONFIG_DMA_TIMEOUT_CHECK_INTERVAL_MS 100
#define CONFIG_ASYNC_IO_QUEUE_TIMEOUT_MS 5000 // 5s timeout for pending I/O in queue

#define CONFIG_AHCI_DRIVER 1
#define CONFIG_AHCI_MAX_RETRIES 3
#define CONFIG_AHCI_MAX_COMRESET_ATTEMPTS 3

#define CONFIG_KEYBOARD_BUFFER_SIZE 256

#define CONFIG_SERIAL_BAUD_RATE 115200

#define CONFIG_ACPI_DEBUG 0
#define CONFIG_ACPI_USE_XSDT 1
#define CONFIG_ACPI_FALLBACK_QEMU 1

#define CONFIG_KMALLOC_MIN_SIZE 16
#define CONFIG_KMALLOC_ALIGNMENT 16

#ifndef CONFIG_DEBUG_ENABLED
#define CONFIG_DEBUG_ENABLED 0
#endif

#ifndef CONFIG_DEBUG_MODE
#define CONFIG_DEBUG_MODE 0
#endif

#ifndef CONFIG_RUN_STARTUP_TESTS
#define CONFIG_RUN_STARTUP_TESTS 0
#endif

#define CONFIG_DEBUG_PMM 0
#define CONFIG_DEBUG_VMM 0
#define CONFIG_DEBUG_PROCESS 0
#define CONFIG_DEBUG_SCHEDULER 0
#define CONFIG_DEBUG_WORKFLOW 0
#define CONFIG_DEBUG_TAGFS 0

#define CONFIG_GUIDE_BATCH_SIZE 16
#define CONFIG_PREFETCH_ENABLED 1
#define CONFIG_CACHE_LINE_SIZE 64 // x86-64 standard

#ifndef CONFIG_START_USERSPACE
#define CONFIG_START_USERSPACE 1
#endif

_Static_assert(CONFIG_TAGFS_BLOCK_SIZE == CONFIG_PAGE_SIZE,
               "CONFIG_TAGFS_BLOCK_SIZE must match CONFIG_PAGE_SIZE");
_Static_assert((CONFIG_USER_STACK_SIZE % CONFIG_PAGE_SIZE) == 0,
               "CONFIG_USER_STACK_SIZE must be page-aligned");
_Static_assert(CONFIG_USER_STACK_SIZE >= 4096,
               "CONFIG_USER_STACK_SIZE must be at least 4KB");
_Static_assert((CONFIG_USER_HEAP_INITIAL_SIZE % CONFIG_PAGE_SIZE) == 0,
               "CONFIG_USER_HEAP_INITIAL_SIZE must be page-aligned");
_Static_assert(CONFIG_USER_HEAP_MAX_SIZE >= CONFIG_USER_HEAP_INITIAL_SIZE,
               "CONFIG_USER_HEAP_MAX_SIZE must be >= initial size");

#endif // KERNEL_CONFIG_H
