#ifndef KERNEL_CONFIG_H
#define KERNEL_CONFIG_H

#include "boxos_limits.h"

#define CONFIG_KERNEL_PHYS_ADDR 0x100000ULL
#define CONFIG_KERNEL_VMA_OFFSET 0xFFFFFFFF80000000ULL

#define CONFIG_PAGE_SIZE 4096

#define CONFIG_KERNEL_STACK_PAGES 4
#define CONFIG_KERNEL_STACK_GUARD_PAGES 1
#define CONFIG_KERNEL_STACK_TOTAL_PAGES (CONFIG_KERNEL_STACK_PAGES + CONFIG_KERNEL_STACK_GUARD_PAGES)
#define CONFIG_USER_STACK_SIZE_KB 64
#define CONFIG_USER_STACK_SIZE (CONFIG_USER_STACK_SIZE_KB * 1024)
#define CONFIG_USER_STACK_PAGES (CONFIG_USER_STACK_SIZE / CONFIG_PAGE_SIZE)
#define CONFIG_USER_STACK_GUARD_PAGES 1
#define CONFIG_USER_STACK_TOTAL_PAGES (CONFIG_USER_STACK_PAGES + CONFIG_USER_STACK_GUARD_PAGES)

#define CONFIG_USER_HEAP_INITIAL_SIZE (64 * 1024)
#define CONFIG_USER_HEAP_MAX_SIZE BOXOS_USER_HEAP_MAX_SIZE
#define CONFIG_USER_HEAP_INITIAL_PAGES (CONFIG_USER_HEAP_INITIAL_SIZE / CONFIG_PAGE_SIZE)

#define CONFIG_PROC_MAX_BINARY_SIZE BOXOS_PROC_MAX_BINARY_SIZE


#define CONFIG_SYSCALL_VECTOR 0x80

#define CONFIG_ATA_TIMEOUT_MS 5000

#define CONFIG_ATA_IO_TIMEOUT_MS 30000

#define CONFIG_ATA_MAX_RETRIES 3

#define CONFIG_ATA_LIVENESS_MS 5000

#ifndef CONFIG_BMIDE_WEDGE_SELFTEST
#define CONFIG_BMIDE_WEDGE_SELFTEST 0
#endif

#define CONFIG_TLB_SHOOTDOWN_PANIC_MS         5000U
#define CONFIG_TLB_SHOOTDOWN_SPIN_BACKSTOP    2000000000ULL
#define CONFIG_TLB_SHOOTDOWN_TSC_FALLBACK_MHZ 1000ULL

#define CONFIG_TOUCH_IRQ_RING_SIZE           64U

#define CONFIG_TOUCH_REACT_DEPTH_MAX 4U
#define CONFIG_TOUCH_REACT_STACK_MARGIN 8192U
_Static_assert(CONFIG_KERNEL_STACK_PAGES * CONFIG_PAGE_SIZE >=
               CONFIG_TOUCH_REACT_DEPTH_MAX * 2560,
               "REACT depth-count fallback must fit the smallest REACT-capable kernel stack");

#define CONFIG_PHYS_ZONE_DMA32_END 0x40000000ULL
#define CONFIG_PHYS_ZONE_USER_END  0x100000000ULL

#define CONFIG_AHCI_DRIVER 1
#define CONFIG_AHCI_MAX_RETRIES 3
#define CONFIG_AHCI_MAX_COMRESET_ATTEMPTS 3
#define CONFIG_AHCI_CMD_TIMEOUT_MS 2000
#define CONFIG_AHCI_IO_TIMEOUT_MS 30000

#ifndef CONFIG_AHCI_SELFTEST
#define CONFIG_AHCI_SELFTEST 0
#endif


#define CONFIG_SCHED_MIN_TICK_HZ      10
#define CONFIG_SCHED_MAX_TICK_HZ      500
#define CONFIG_SCHED_DEFAULT_TICK_HZ  250

#define CONFIG_SCHED_PARK_IDLE_TICKS    100
#define CONFIG_SCHED_UNPARK_LOAD_THRESH 1

#define CONFIG_SCHED_AFFINITY_WARM_TICKS 5

#define CONFIG_SCHED_RECALC_INTERVAL  10

#define CONFIG_SCHED_MAX_CONSECUTIVE_RUNS 5
#define CONFIG_SCHED_MIN_FAIRNESS         2
#define CONFIG_SCHED_MAX_FAIRNESS         20
#define CONFIG_SCHED_MIN_STARVATION       10
#define CONFIG_SCHED_MAX_STARVATION       100

#define CONFIG_RUNQUEUE_INITIAL_CAP   64
#define CONFIG_RUNQUEUE_MAX_CAP       4096

#define CONFIG_PROCESS_HASH_SIZE      256
#define CONFIG_PROCESS_CLEANUP_BATCH  8
#define CONFIG_STRAND_REAP_BATCH      16
#define CONFIG_PROCESS_POISON_MAGIC   0xDEADDEADu

#ifndef CONFIG_KB_REPEAT_DELAY_MS
#define CONFIG_KB_REPEAT_DELAY_MS  500
#endif
#ifndef CONFIG_KB_REPEAT_RATE_MS
#define CONFIG_KB_REPEAT_RATE_MS    33
#endif
#ifndef CONFIG_KB_HOLD_ONE_CHAR_MS
#define CONFIG_KB_HOLD_ONE_CHAR_MS 500
#endif
_Static_assert(CONFIG_KB_REPEAT_DELAY_MS >= CONFIG_KB_HOLD_ONE_CHAR_MS,
               "keyboard repeat starts before the hold this file promises "
               "yields one character: raise CONFIG_KB_REPEAT_DELAY_MS or "
               "lower CONFIG_KB_HOLD_ONE_CHAR_MS, and say which you meant");
_Static_assert(CONFIG_KB_REPEAT_RATE_MS > 0,
               "a repeat interval of zero is a key that never stops");

#define CONFIG_ACPI_DEBUG 0

#define CONFIG_BCDC_MAX_DICTS         256
#define CONFIG_BCDC_DEFAULT_DICT_SIZE 8192
#define CONFIG_BCDC_POLICY_INITIAL    16
#define CONFIG_BCDC_POLICY_MAX        4096
#define CONFIG_BCDC_LZ_HASH_BITS      12

#ifndef CONFIG_DEBUG_ENABLED
#define CONFIG_DEBUG_ENABLED 0
#endif

#ifndef CONFIG_DEBUG_MODE
#define CONFIG_DEBUG_MODE 0
#endif

#ifndef CONFIG_RUN_STARTUP_TESTS
#define CONFIG_RUN_STARTUP_TESTS 1
#endif

#define CONFIG_PERF_TRACE 0

#define CONFIG_CACHE_LINE_SIZE 64

#ifndef CONFIG_START_USERSPACE
#define CONFIG_START_USERSPACE 1
#endif

#define CONFIG_MAX_CORES 256

_Static_assert((CONFIG_USER_STACK_SIZE % CONFIG_PAGE_SIZE) == 0,
               "CONFIG_USER_STACK_SIZE must be page-aligned");
_Static_assert(CONFIG_USER_STACK_SIZE >= 4096,
               "CONFIG_USER_STACK_SIZE must be at least 4KB");
_Static_assert((CONFIG_USER_HEAP_INITIAL_SIZE % CONFIG_PAGE_SIZE) == 0,
               "CONFIG_USER_HEAP_INITIAL_SIZE must be page-aligned");
_Static_assert(CONFIG_USER_HEAP_MAX_SIZE >= CONFIG_USER_HEAP_INITIAL_SIZE,
               "CONFIG_USER_HEAP_MAX_SIZE must be >= initial size");

#endif