#ifndef BOXOS_ERROR_H
#define BOXOS_ERROR_H

#include "ktypes.h"

typedef enum {
    OK = 0,

    // General Errors (1-99)
    ERR_UNKNOWN = 1,
    ERR_NOT_IMPLEMENTED = 2,
    ERR_INVALID_ARGUMENT = 3,
    ERR_NULL_POINTER = 4,
    ERR_OUT_OF_RANGE = 5,
    ERR_BUFFER_TOO_SMALL = 6,
    ERR_TIMEOUT = 7,
    ERR_BUSY = 8,
    ERR_WOULD_BLOCK = 9,
    ERR_ALIGNMENT = 10,
    ERR_CORRUPTED = 11,
    ERR_INTERNAL = 12,
    ERR_NOT_INITIALIZED = 13,
    ERR_ALREADY_INITIALIZED = 14,
    ERR_INVALID_STATE = 15,
    ERR_RETRY = 16,
    ERR_UNSUPPORTED = 17,
    ERR_VERSION_MISMATCH = 18,
    ERR_CHECKSUM = 19,

    // Memory Errors (100-199)
    ERR_NO_MEMORY = 100,
    ERR_INVALID_ADDRESS = 101,
    ERR_PAGE_FAULT = 102,
    ERR_ALREADY_MAPPED = 103,
    ERR_NOT_MAPPED = 104,
    ERR_PERMISSION_DENIED_MEM = 105,
    ERR_HEAP_EXHAUSTED = 106,
    ERR_STACK_OVERFLOW = 107,
    ERR_BUFFER_OVERFLOW = 108,
    ERR_INVALID_BUFFER_ID = 109,
    ERR_BUFFER_IN_USE = 110,
    ERR_BUFFER_LIMIT_EXCEEDED = 111,
    ERR_MAPPING_FAILED = 112,
    ERR_UNMAP_FAILED = 113,
    ERR_TLB_FLUSH_FAILED = 114,
    ERR_PHYS_ADDR_EXCEEDED = 115,
    ERR_PCID_EXHAUSTED = 116,

    // I/O Errors (200-299)
    ERR_IO = 200,
    ERR_READ_FAILED = 201,
    ERR_WRITE_FAILED = 202,
    ERR_DEVICE_NOT_READY = 203,
    ERR_DEVICE_ERROR = 204,
    ERR_END_OF_FILE = 205,
    ERR_DISK_FULL = 206,
    ERR_BAD_SECTOR = 207,
    ERR_IO_PENDING = 208,
    ERR_IO_QUEUE_FULL = 209,
    ERR_IO_CANCELLED = 210,
    ERR_DMA_FAILED = 211,
    ERR_DMA_TIMEOUT = 212,
    ERR_SECTOR_READ_FAILED = 213,
    ERR_SECTOR_WRITE_FAILED = 214,

    // Filesystem Errors (300-399)
    ERR_FILE_NOT_FOUND = 300,
    ERR_OBJECT_NOT_FOUND = 301,
    ERR_TAG_NOT_FOUND = 302,
    ERR_ALREADY_EXISTS = 303,
    ERR_INVALID_TAG = 304,
    ERR_TAG_LIMIT_EXCEEDED = 305,
    ERR_OBJECT_CORRUPTED = 306,
    ERR_JOURNAL_FULL = 307,
    ERR_JOURNAL_CORRUPTED = 308,
    ERR_METADATA_CORRUPTED = 309,
    ERR_TAG_REGISTRY_FULL = 310,
    ERR_FILE_TABLE_CORRUPT = 311,
    ERR_METADATA_POOL_FULL = 312,
    ERR_BLOCK_ALLOC_FAILED = 313,
    ERR_BLOCK_FREE_FAILED = 314,
    ERR_FILE_HANDLE_INVALID = 315,
    ERR_FILE_HANDLE_IN_USE = 316,
    ERR_EXTENT_INVALID = 317,
    ERR_BITMAP_FULL = 318,
    ERR_SUPERBLOCK_INVALID = 319,
    ERR_BOOT_HINTS_MISSING = 320,
    ERR_SNAPSHOT_LIMIT = 321,
    ERR_SNAPSHOT_NOT_FOUND = 322,
    ERR_DEDUP_FAILED = 323,
    ERR_SELF_HEAL_FAILED = 324,

    // Process Errors (400-499)
    ERR_PROCESS_NOT_FOUND = 400,
    ERR_INVALID_PID = 401,
    ERR_PROCESS_LIMIT_EXCEEDED = 402,
    ERR_PROCESS_TERMINATED = 403,
    ERR_PROCESS_BLOCKED = 404,
    ERR_INVALID_ELF = 405,
    ERR_BINARY_TOO_LARGE = 406,
    ERR_SPAWN_FAILED = 407,
    ERR_PROCESS_RUNNING = 408,
    ERR_PROCESS_DESTROYING = 409,
    ERR_CABIN_CREATE_FAILED = 410,
    ERR_PID_EXHAUSTED = 411,
    ERR_TAG_OVERFLOW_FAILED = 412,
    ERR_FPU_INIT_FAILED = 413,
    ERR_STACK_ALLOC_FAILED = 414,

    // Security Errors (500-599)
    ERR_ACCESS_DENIED = 500,
    ERR_PERMISSION_DENIED = 501,
    ERR_SECURITY_VIOLATION = 502,
    ERR_TAG_MISMATCH = 503,
    ERR_INVALID_OPERATION = 504,
    ERR_PRIVILEGE_REQUIRED = 505,
    ERR_SANDBOX_VIOLATION = 506,

    // Hardware Errors (600-699)
    ERR_HARDWARE = 600,
    ERR_INVALID_DEVICE = 601,
    ERR_DEVICE_BUSY = 602,
    ERR_KEYBOARD_BUFFER_FULL = 603,
    ERR_VGA_ERROR = 604,
    ERR_ATA_ERROR = 605,
    ERR_PCI_ERROR = 606,
    ERR_USB_ERROR = 607,
    ERR_XHCI_ERROR = 608,
    ERR_AHCI_ERROR = 609,
    ERR_TIMER_ERROR = 610,
    ERR_INTERRUPT_ERROR = 611,
    ERR_CPU_ERROR = 612,

    // Network Errors (700-799) - reserved

    // ACPI Errors (800-899)
    ERR_ACPI_NOT_FOUND = 800,
    ERR_ACPI_INVALID_TABLE = 801,
    ERR_ACPI_CHECKSUM_FAILED = 802,
    ERR_ACPI_PARSE_ERROR = 803,
    ERR_ACPI_MADT_NOT_FOUND = 804,
    ERR_ACPI_FADT_NOT_FOUND = 805,

    // Pocket System Errors (900-999)
    ERR_POCKET_RING_FULL = 900,
    ERR_RESULT_RING_FULL = 901,
    ERR_INVALID_POCKET = 902,
    ERR_INVALID_DECK_ID = 903,
    ERR_INVALID_OPCODE = 904,
    ERR_PREFIX_CHAIN_TOO_LONG = 905,
    ERR_POCKET_PROCESSING_FAILED = 906,
    ERR_PENDING_QUEUE_FULL = 907,
    ERR_KCORE_QUEUE_FULL = 908,
    ERR_KCORE_SUBMIT_FAILED = 909,
    ERR_RESULT_NOT_READY = 910,
    ERR_RESULT_STASH_FULL = 911,

    // Routing/IPC Errors (940-949)
    ERR_ROUTE_TARGET_FULL    = 940,
    ERR_ROUTE_NO_SUBSCRIBERS = 941,
    ERR_ROUTE_SELF           = 942,
    ERR_LISTEN_TABLE_FULL    = 943,
    ERR_LISTEN_ALREADY       = 944,
    ERR_ROUTE_INVALID_TAG    = 945,

    ERR_POCKET_FAILED        = 950,

    // Scheduler Errors (960-969)
    ERR_SCHEDULER_LOCKED = 960,
    ERR_RUNQUEUE_FULL = 961,
    ERR_RUNQUEUE_EMPTY = 962,
    ERR_HOME_CORE_INVALID = 963,
    ERR_WORK_STEAL_FAILED = 964,

    // Boot Errors (970-979)
    ERR_BOOT_INFO_INVALID = 970,
    ERR_E820_FAILED = 971,
    ERR_A20_FAILED = 972,
    ERR_LONG_MODE_FAILED = 973,
    ERR_KERNEL_LOAD_FAILED = 974,

    ERR_MAX = 999
} error_t;

#define IS_ERROR(err) ((err) != OK)
#define IS_SUCCESS(err) ((err) == OK)

#define PROPAGATE(expr) do { \
    error_t _err = (expr); \
    if (IS_ERROR(_err)) { \
        return _err; \
    } \
} while (0)

const char* ErrorString(error_t err);

#endif // BOXOS_ERROR_H
