#!/usr/bin/env python3
# ============================================================================
# gen_unicode_escape.py — offline generator for the Unicode tables behind
# boxcxx <__bits/unicode_escape> (Ф30f-3: [format.string.escaped]).
#
# NOT a build dependency. The kernel build compiles the baked constexpr edge
# arrays; run this only to (re)generate them against a newer Unicode release.
#
#   python3 tools/gen_unicode_escape.py                    # fetch latest UCD
#   python3 tools/gen_unicode_escape.py --ucd /path/to/ucd # use a local copy
#
# Two predicates come out, exactly the two [format.string.escaped]/2.2.1.2
# asks for:
#
#   NeedsEscapeCategory(cp)  General_Category in group Separator (Z) or
#                            Other (C) -- Zs/Zl/Zp/Cc/Cf/Cs/Co/Cn. Unassigned
#                            code points are Cn and therefore in the set; they
#                            are taken both from the explicit Cn lines and from
#                            anything the file does not list at all, so a
#                            truncated input can only ever over-escape.
#                            U+0020 stays IN the set: it is Zs, and the rule
#                            that spares it belongs to the escaping engine.
#
#   IsGraphemeExtend(cp)     the Grapheme_Extend property. NOT
#                            Grapheme_Cluster_Break=Extend, which is what both
#                            libstdc++ and libc++ use -- UAX #29 defines that
#                            as Grapheme_Extend union Emoji_Modifier, and the
#                            normative text says Grapheme_Extend.
#
# Both are emitted as sorted edge arrays: runs alternate outside/inside
# starting outside, so membership is "the number of edges <= cp is odd". One
# binary search, no packing, nothing to get subtly wrong at 3am.
# ============================================================================
import argparse
import sys
import urllib.request
from pathlib import Path

MAXCP = 0x10FFFF
Z_OR_C = {"Cc", "Cf", "Cs", "Co", "Cn", "Zs", "Zl", "Zp"}

UCD_BASE = "https://www.unicode.org/Public/UCD/latest/ucd/"
GC_FILE = "extracted/DerivedGeneralCategory.txt"
DCP_FILE = "DerivedCoreProperties.txt"

HEADER = Path(__file__).resolve().parent.parent / (
    "src/userspace/boxcxx/include/std/__bits/unicode_escape")


def fetch(path, ucd_dir):
    """Return the text of one UCD file, from disk if given, else from unicode.org."""
    if ucd_dir:
        return (Path(ucd_dir) / Path(path).name).read_text(encoding="utf-8")
    with urllib.request.urlopen(UCD_BASE + path, timeout=120) as r:
        return r.read().decode("utf-8")


def parse(text):
    """Yield (first, last, property) for every data line."""
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [f.strip() for f in line.split(";")]
        if len(fields) < 2:
            continue
        lo, _, hi = fields[0].partition("..")
        yield int(lo, 16), int(hi or lo, 16), fields[1]


def merge(pairs):
    """Sort and coalesce (first,last) pairs into disjoint, adjacent-free runs."""
    out = []
    for lo, hi in sorted(pairs):
        if out and lo <= out[-1][1] + 1:
            out[-1][1] = max(out[-1][1], hi)
        else:
            out.append([lo, hi])
    return [(lo, hi) for lo, hi in out]


def complement(runs):
    """Everything in [0, MAXCP] that `runs` does not cover."""
    out, prev = [], 0
    for lo, hi in runs:
        if lo > prev:
            out.append((prev, lo - 1))
        prev = hi + 1
    if prev <= MAXCP:
        out.append((prev, MAXCP))
    return out


def edges(runs):
    flat = []
    for lo, hi in runs:
        flat.append(lo)
        flat.append(hi + 1)
    return flat


def check(runs, flat):
    """Membership by run must agree with membership by edge parity, everywhere."""
    inside = set()
    for lo, hi in runs:
        inside.update(range(lo, hi + 1))
    import bisect
    for cp in range(0, MAXCP + 1):
        if (bisect.bisect_right(flat, cp) & 1) != (cp in inside):
            raise SystemExit("edge encoding disagrees with the runs at U+%05X" % cp)


def array(name, flat):
    out = ["inline constexpr char32_t %s[] = {" % name]
    for i in range(0, len(flat), 8):
        out.append("    " + ", ".join("0x%05X" % v for v in flat[i:i + 8]) + ",")
    out.append("};")
    out.append("inline constexpr unsigned %s = %d;"
               % (name[:-1] + "Count", len(flat)))
    return "\n".join(out)


PREAMBLE = '''// boxcxx — <__bits/unicode_escape>
//
// The two Unicode predicates [format.string.escaped] needs, and nothing else.
//
// THIS WHOLE FILE IS GENERATED by tools/gen_unicode_escape.py — not just the
// arrays. Re-running that script overwrites every line here, so nothing
// hand-written may live in this file: it holds UCD facts and nothing else.
// The UTF-8 decoder that consumes these predicates lives in
// <__bits/format_escape>, next to the escaping algorithm that drives it.
//
// Source data: %(gc)s
//              %(dcp)s
//
// [format.string.escaped]/2.2.1.2 escapes a character when either
//   * its General_Category is in group Separator (Z) or Other (C) — that is
//     Zs/Zl/Zp/Cc/Cf/Cs/Co/Cn, where Cn (unassigned) is by far the largest
//     part. U+0020 is in this set; the rule that spares it lives in the
//     escaping engine, not here (libstdc++ draws the line in the same place).
//   * or it has Grapheme_Extend=Yes *and* the character before it in the
//     source was itself escaped. The positional half of that rule is the
//     engine's business; this header only answers "is it Grapheme_Extend".
//
// Both libstdc++ 15.2 and libc++ 22.1 answer the second question with
// Grapheme_Cluster_Break=Extend, which UAX #29 defines as Grapheme_Extend
// union Emoji_Modifier. The five Fitzpatrick modifiers U+1F3FB..U+1F3FF are
// therefore escaped-after-an-escape by both of them and are deliberately not
// escaped here: the normative text says Grapheme_Extend, and those five have
// Grapheme_Base=Yes. That is the only intentional divergence — a sweep of all
// 1114112 code points against both libraries found no other disagreement that
// the Unicode 16 -> 17 data bump does not account for.
//
// Storage: sorted edge arrays, read by InRuns in <__bits/unicode_runs> — the
// same reader <__bits/unicode_wctype> uses, which is why it lives outside both
// generated files rather than being emitted twice.
#ifndef BOXCXX_BITS_UNICODE_ESCAPE
#define BOXCXX_BITS_UNICODE_ESCAPE

#include <__bits/unicode_runs>

namespace std {
namespace __unicode {

'''

EPILOGUE = '''
// General_Category in group Separator (Z) or Other (C). U+0020 is included.
constexpr bool NeedsEscapeCategory(char32_t cp) noexcept
{
    return InRuns(kEscapeCategoryEdges, kEscapeCategoryEdgeCount, cp);
}

// The Unicode property Grapheme_Extend=Yes.
constexpr bool IsGraphemeExtend(char32_t cp) noexcept
{
    return InRuns(kGraphemeExtendEdges, kGraphemeExtendEdgeCount, cp);
}

} // namespace __unicode
} // namespace std

#endif // BOXCXX_BITS_UNICODE_ESCAPE
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ucd", help="directory holding the two UCD files")
    ap.add_argument("--out", default=str(HEADER))
    args = ap.parse_args()

    gc_text = fetch(GC_FILE, args.ucd)
    dcp_text = fetch(DCP_FILE, args.ucd)
    gc_name = gc_text.splitlines()[0].strip("# ")
    dcp_name = dcp_text.splitlines()[0].strip("# ")

    gc = list(parse(gc_text))
    listed = merge([(lo, hi) for lo, hi, _ in gc])
    zc = [(lo, hi) for lo, hi, p in gc if p in Z_OR_C]
    cat = merge(zc + complement(listed))
    ge = merge([(lo, hi) for lo, hi, p in parse(dcp_text)
                if p == "Grapheme_Extend"])
    if not cat or not ge:
        raise SystemExit("UCD parse produced an empty table — refusing to write")

    cat_e, ge_e = edges(cat), edges(ge)
    check(cat, cat_e)
    check(ge, ge_e)

    text = (PREAMBLE % {"gc": gc_name, "dcp": dcp_name}
            + array("kEscapeCategoryEdges", cat_e) + "\n\n"
            + array("kGraphemeExtendEdges", ge_e) + "\n"
            + EPILOGUE)
    Path(args.out).write_text(text)

    print("%s: %d category runs, %d grapheme-extend runs, %d bytes of rodata"
          % (args.out, len(cat), len(ge), 4 * (len(cat_e) + len(ge_e))))
    print("escaped by category: %d code points" % sum(h - l + 1 for l, h in cat))
    print("grapheme-extend:     %d code points" % sum(h - l + 1 for l, h in ge))


if __name__ == "__main__":
    sys.exit(main())
