#!/usr/bin/env bash
# ============================================================================
# tools/make_bochsrc.sh
#
# Generate bochsrc.txt for BoxOS. Driven entirely from environment variables
# so the top-level Makefile can pass build-time toggles cleanly.
#
# Required env vars:
#   BOCHS_RC          output path (e.g. build/bochsrc.txt)
#   IMAGE             path to BoxOS disk image
#   BOCHS_BIOS        path to BIOS-bochs-latest (used when UEFI=off)
#   BOCHS_VGABIOS     path to VGABIOS-lgpl-latest.bin
#
# Optional env vars (defaults shown):
#   CORES=1                  vCPU count (Bochs SMP requires --enable-smp)
#   MEM=512M                 e.g. 512M, 4G, 2048 (raw integer = MB)
#   BOCHS_DISP_LIB=sdl2      sdl2|sdl|x|win32|term|nogui
#   BOCHS_DATA_DIRS=         space-separated dirs containing keymaps/
#   UEFI=off                 on -> use OVMF.fd as romimage + ESP disk
#   OVMF_FD=                 path to OVMF.fd (required when UEFI=on)
#   UEFI_ESP_IMG=            path to ESP FAT image (required when UEFI=on)
#   GDB=off                  on -> emit gdbstub: section
#   LOG=off                  on -> info/debug events report to log
#   BOCHS_LOG=bochs.log      log file path
# ============================================================================

set -euo pipefail

OUT="${BOCHS_RC:?BOCHS_RC is required}"
IMG="${IMAGE:?IMAGE is required}"
VGA="${BOCHS_VGABIOS:?BOCHS_VGABIOS is required}"

UEFI_MODE="${UEFI:-off}"
CORES="${CORES:-1}"
MEM_RAW="${MEM:-512M}"
CPU_MODEL="${BOCHS_CPU:-corei7_haswell_4770}"
CPU_IPS="${BOCHS_IPS:-50000000}"
DISP="${BOCHS_DISP_LIB:-sdl2}"
GDB="${GDB:-off}"
LOG_VERBOSE="${LOG:-off}"
LOGFILE="${BOCHS_LOG:-bochs.log}"
DATA_DIRS="${BOCHS_DATA_DIRS:-}"

# Convert MEM (e.g. 4G, 512M, 2048) -> integer megabytes for `megs:` directive.
case "$MEM_RAW" in
    *[Gg]) MEM_MB=$(( ${MEM_RAW%[Gg]} * 1024 )) ;;
    *[Mm]) MEM_MB="${MEM_RAW%[Mm]}" ;;
    *)     MEM_MB="$MEM_RAW" ;;
esac

INFO_ACTION="ignore"
DBG_ACTION="ignore"
if [ "$LOG_VERBOSE" = "on" ]; then
    INFO_ACTION="report"
    DBG_ACTION="report"
fi

# Pick the keymap file matching the chosen display library. Bochs ships
# separate sets — feeding an X11 keymap to SDL2 yields "unknown host key
# name 'XK_0' (wrong keymap?)" warnings on every keystroke.
case "$DISP" in
    sdl2)  KEYMAP_BASENAME="sdl2-pc-us.map" ;;
    sdl)   KEYMAP_BASENAME="sdl-pc-us.map" ;;
    x)     KEYMAP_BASENAME="x11-pc-us.map" ;;
    *)     KEYMAP_BASENAME="" ;;  # term/nogui/win32 — leave keymap unset
esac

KEYMAP_PATH=""
if [ -n "$KEYMAP_BASENAME" ] && [ -n "$DATA_DIRS" ]; then
    for d in $DATA_DIRS; do
        candidate="$d/keymaps/$KEYMAP_BASENAME"
        if [ -f "$candidate" ]; then
            KEYMAP_PATH="$candidate"
            break
        fi
    done
fi

# UEFI vs BIOS romimage.
#
# translation=lba: force LBA-only addressing for Bochs's emulated BIOS. With
# translation=auto (Bochs default) disks <504 MB are reported as CHS-only,
# and INT 13h AH=42h (Extended Read via DAP) returns CF=1 — that's exactly
# what stage2 uses to read the TagFS superblock at sector 1034, and what
# real-hardware boot also uses. Forcing LBA mirrors the EDD mode every
# modern BIOS / UEFI / OVMF advertises, so behaviour matches real boot.
if [ "$UEFI_MODE" = "on" ]; then
    OVMF="${OVMF_FD:?OVMF_FD is required when UEFI=on}"
    ESP="${UEFI_ESP_IMG:?UEFI_ESP_IMG is required when UEFI=on}"
    ROM_LINE='romimage:    file="'"$OVMF"'"'
    DISK_LINES='ata0:        enabled=1, ioaddr1=0x1f0, ioaddr2=0x3f0, irq=14
ata0-master: type=disk, path="'"$ESP"'", mode=flat, cylinders=0, heads=0, spt=0, translation=lba
ata0-slave:  type=disk, path="'"$IMG"'", mode=flat, cylinders=0, heads=0, spt=0, translation=lba'
    BOOT_LINE='boot: disk'
else
    BIOS="${BOCHS_BIOS:?BOCHS_BIOS is required when UEFI=off}"
    ROM_LINE='romimage:    file="'"$BIOS"'"'
    DISK_LINES='ata0:        enabled=1, ioaddr1=0x1f0, ioaddr2=0x3f0, irq=14
ata0-master: type=disk, path="'"$IMG"'", mode=flat, cylinders=0, heads=0, spt=0, translation=lba'
    BOOT_LINE='boot: disk'
fi

cat >"$OUT" <<EOF
# ===========================================================================
# Auto-generated by tools/make_bochsrc.sh - DO NOT EDIT BY HAND.
# Re-generate via:  make run EMU=bochs [...flags]
# Mode: UEFI=$UEFI_MODE  Display=$DISP  Cores=$CORES  Mem=${MEM_MB}M
# ===========================================================================

# ---- Boot order ----
$BOOT_LINE

# ---- Firmware ROM ----
$ROM_LINE
vgaromimage: file="$VGA"

# ---- CPU ----
# Override model/ips via BOCHS_CPU= and BOCHS_IPS= env when invoking make.
# Run \`bochs --help cpu\` to list every supported model on this build.
cpu: count=$CORES, model=$CPU_MODEL, ips=$CPU_IPS, reset_on_triple_fault=0

# ---- RAM ----
megs: $MEM_MB

# ---- IDE disks ----
# Geometry left at 0/0/0 -> Bochs autodetects from image size; this avoids
# "specified geometry doesn't fit on disk image" panics from rounding.
$DISK_LINES

# ---- Display ----
config_interface: textconfig
display_library:  $DISP

# ---- Wall-clock alignment ----
clock: sync=realtime, time0=local

# ---- Logging ----
log: $LOGFILE
panic: action=ask
error: action=report
info:  action=$INFO_ACTION
debug: action=$DBG_ACTION

# ---- Debug helpers ----
magic_break:  enabled=1     # 'xchg bx,bx' instruction -> break into debugger
port_e9_hack: enabled=1     # outb to port 0xE9 -> host stdout (kernel printf)

# ---- Input ----
mouse: enabled=0
EOF

if [ -n "$KEYMAP_PATH" ]; then
    printf 'keyboard: keymap="%s", type=mf\n' "$KEYMAP_PATH" >>"$OUT"
fi

# ---- Serial COM1 (optional) ----
# Wire COM1 so BoxOS's kernel log (TX) and serial console (RX, see
# serial_console_init) reach the host. BOCHS_COM1_MODE picks the Bochs backend:
#   file           TX only -> a log file (BOCHS_COM1_DEV = path)
#   socket-server  bidirectional TCP; Bochs listens, a client drives the shell
#                  (BOCHS_COM1_DEV = host:port) — this is the headless console
# Left unset by default (interactive `make run EMU=bochs` uses the GUI keyboard).
if [ -n "${BOCHS_COM1_MODE:-}" ]; then
    printf 'com1: enabled=1, mode=%s, dev=%s\n' \
        "$BOCHS_COM1_MODE" \
        "${BOCHS_COM1_DEV:?BOCHS_COM1_DEV is required when BOCHS_COM1_MODE is set}" >>"$OUT"
fi

if [ "$GDB" = "on" ]; then
    cat >>"$OUT" <<'EOF'

# ---- GDB remote debug stub (requires Bochs built with --enable-gdb-stub) ----
# Connect from host: target remote :1234
gdbstub: enabled=1, port=1234, text_base=0, data_base=0, bss_base=0
EOF
fi
