#ifndef BOXOS_SIZES_H
#define BOXOS_SIZES_H

#define PAGE_SIZE              4096

#define LARGE_PAGE_2M_SIZE     0x200000UL
#define LARGE_PAGE_2M_MASK     (LARGE_PAGE_2M_SIZE - 1)
#define LARGE_PAGE_2M_PAGES    (LARGE_PAGE_2M_SIZE / PAGE_SIZE)


#endif