#ifndef BOXOS_LIMITS_H
#define BOXOS_LIMITS_H

#define MAX_PROCESSES      256
#define MAX_OPEN_FILES     256

#define EVENT_RING_SIZE    2048  // Power of 2
#define MAX_PENDING_RESULTS 256

#define IDT_ENTRIES        256
#define ATA_SECTOR_SIZE    512

#define TAGFS_MAX_FILES    1024  // Phase 1 limit
#define TAGFS_MAX_TAG_INDEX 1024
#define TAGFS_INODE_SIZE   512
#define JOURNAL_ENTRY_COUNT 512

#define KEYBOARD_BUFFER_SIZE    256
#define KEYBOARD_LINE_BUFFER_SIZE 256
#define INPUT_BUFFER_SIZE       256

#define XHCI_MAX_SLOTS     256

#define AHCI_FIS_SIZE      256
#define AHCI_FIS_ALIGN     256
#define AHCI_CLB_SIZE      1024
#define AHCI_CLB_ALIGN     1024

#endif // BOXOS_LIMITS_H
