#ifndef BOXOS_ADDRESSES_H
#define BOXOS_ADDRESSES_H

#include "cabin_layout.h"

#define CABIN_INFO_VADDR          CABIN_INFO_ADDR
#define POCKET_RING_VADDR         CABIN_POCKET_RING_ADDR
#define RESULT_RING_VADDR         CABIN_RESULT_RING_ADDR

#define CPU_CAPS_PAGE_ADDR        0x0000000007FFFF000ULL

#define USER_STACK_TOP            0x00007FFFFFFFE000ULL

#endif