#ifndef VIDEO_COLORS_H
#define VIDEO_COLORS_H

#define VIDEO_BLACK           0x0
#define VIDEO_BLUE            0x1
#define VIDEO_GREEN           0x2
#define VIDEO_CYAN            0x3
#define VIDEO_RED             0x4
#define VIDEO_MAGENTA         0x5
#define VIDEO_BROWN           0x6
#define VIDEO_LIGHT_GRAY      0x7
#define VIDEO_DARK_GRAY       0x8
#define VIDEO_LIGHT_BLUE      0x9
#define VIDEO_LIGHT_GREEN     0xA
#define VIDEO_LIGHT_CYAN      0xB
#define VIDEO_LIGHT_RED       0xC
#define VIDEO_LIGHT_MAGENTA   0xD
#define VIDEO_YELLOW          0xE
#define VIDEO_WHITE           0xF

#define VIDEO_COLOR(fg, bg)   (((bg) << 4) | (fg))
#define VIDEO_FG(attr)        ((attr) & 0x0F)
#define VIDEO_BG(attr)        (((attr) >> 4) & 0x0F)

#define VIDEO_GRAY_ON_BLACK      VIDEO_COLOR(VIDEO_LIGHT_GRAY,    VIDEO_BLACK)
#define VIDEO_WHITE_ON_BLACK     VIDEO_COLOR(VIDEO_WHITE,          VIDEO_BLACK)
#define VIDEO_BLACK_ON_WHITE     VIDEO_COLOR(VIDEO_BLACK,          VIDEO_WHITE)
#define VIDEO_BLACK_ON_GRAY      VIDEO_COLOR(VIDEO_BLACK,          VIDEO_LIGHT_GRAY)
#define VIDEO_RED_ON_BLACK       VIDEO_COLOR(VIDEO_LIGHT_RED,      VIDEO_BLACK)
#define VIDEO_GREEN_ON_BLACK     VIDEO_COLOR(VIDEO_LIGHT_GREEN,    VIDEO_BLACK)
#define VIDEO_YELLOW_ON_BLACK    VIDEO_COLOR(VIDEO_YELLOW,         VIDEO_BLACK)
#define VIDEO_CYAN_ON_BLACK      VIDEO_COLOR(VIDEO_LIGHT_CYAN,     VIDEO_BLACK)
#define VIDEO_BLUE_ON_BLACK      VIDEO_COLOR(VIDEO_LIGHT_BLUE,     VIDEO_BLACK)
#define VIDEO_MAGENTA_ON_BLACK   VIDEO_COLOR(VIDEO_LIGHT_MAGENTA,  VIDEO_BLACK)
#define VIDEO_WHITE_ON_BLUE      VIDEO_COLOR(VIDEO_WHITE,          VIDEO_BLUE)
#define VIDEO_WHITE_ON_RED       VIDEO_COLOR(VIDEO_WHITE,          VIDEO_RED)
#define VIDEO_BLACK_ON_CYAN      VIDEO_COLOR(VIDEO_BLACK,          VIDEO_CYAN)
#define VIDEO_BLACK_ON_YELLOW    VIDEO_COLOR(VIDEO_BLACK,          VIDEO_YELLOW)

#define VIDEO_ATTR_DEFAULT    VIDEO_GRAY_ON_BLACK
#define VIDEO_ATTR_ERROR      VIDEO_RED_ON_BLACK
#define VIDEO_ATTR_WARNING    VIDEO_YELLOW_ON_BLACK
#define VIDEO_ATTR_SUCCESS    VIDEO_GREEN_ON_BLACK
#define VIDEO_ATTR_HINT       VIDEO_CYAN_ON_BLACK
#define VIDEO_ATTR_PROMPT     VIDEO_CYAN_ON_BLACK
#define VIDEO_ATTR_CONTEXT    VIDEO_YELLOW_ON_BLACK
#define VIDEO_ATTR_INPUT      VIDEO_WHITE_ON_BLACK
#define VIDEO_ATTR_OUTPUT     VIDEO_GRAY_ON_BLACK
#define VIDEO_ATTR_FILENAME   VIDEO_WHITE_ON_BLACK
#define VIDEO_ATTR_TAG        VIDEO_MAGENTA_ON_BLACK
#define VIDEO_ATTR_CURSOR     VIDEO_BLUE_ON_BLACK

#endif